#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yuma Takimoto
# SPDX-License-Identifier: BSD-3-Clause
import sys
ans = 0
for line in sys.stdin:
    line = line.strip()  
    if line:  
        try:
            value = int(line)
        except ValueError: 
            try:
                value = float(line)
            except ValueError: 
                continue
        ans += value
        print(f'{ans}')  
print(f'{ans}')  
