#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yuma Takimoto
import sys
ans = 0
for line in sys.stdin:
    line = line.strip()  
    if line:  
        try:
            value = int(line)
        except ValueError:  
            try:
                value = float(line)
            except ValueError:  
                continue
        ans += value
        print(f'Current total: {ans}')  
print(f'Final total: {ans}')  
